# SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB a KDAB Group company info@kdab.com
# SPDX-FileContributor: Sérgio Martins <sergio.martins@kdab.com>
# SPDX-License-Identifier: LGPL-2.0-or-later

name: macOS CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on:  macos-13

    steps:
      - name: Install Qt 6.6
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.3
          cache: true

      - name: Install dependencies
        run: |
          brew install llvm ninja coreutils

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset=dev
        env:
          CXX: clang++
          LLVM_ROOT: /usr/local/opt/llvm

      - name: Build
        run: cmake --build ./build-dev
